- name: Mkdir folder for nasm
  command: "mkdir -p {{ ffmpeg_source_dir }}/nasm"

- name: Download nasm archive
  command: "wget {{ nasm_url }} chdir={{ ffmpeg_source_dir }}/nasm"

- name: Extract nasm
  command: "tar xjvf {{ ffmpeg_source_dir }}/nasm/{{ nasm_filename }} chdir={{ ffmpeg_source_dir }}/nasm"

- name: Compile nasm
  shell: 'cd {{ ffmpeg_source_dir }}/nasm/{{ nasm_version }}; {{ item }} creates={{ ffmpeg_bin_dir }}/nasm'
  with_items:
    - ./autogen.sh
    - ./configure --prefix={{ ffmpeg_build }} --bindir={{ ffmpeg_bin_dir }}
    - make
    - make install
    - make distclean
